spring:
  application:
    name: eureka

server:
  port: 8762

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ipAddress}:8761/eureka/,http://localhost:8763/eureka/