spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/,http://localhost:8763/eureka/