spring:
  application:
    name: eureka

server:
  port: 8763

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ipAddress}:8761/eureka/,http://127.0.0.1:8762/eureka/